---
- name: "Converge"
  hosts: all
  vars_files:
    - vars.yml
  collections:
    - middleware_automation.jws
    - middleware_automation.common_criteria
  roles:
    - jws
    - jws_common_criteria
