---
- name: Prepare
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Display Ansible version
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: Install required dependencies
      package:
        name: sudo

  pre_tasks:
    - name: "Download latest Apache Tomcat zip file from {{ download_url }}."
      get_url:
        url: "{{ download_url }}"
        dest: "{{ tomcat_zipfile }}"
      when:
        - download_url is defined
